//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogTJMT.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensagensSucesso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensagensSucesso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlogTJMT.Common.Resources.MensagensSucesso", typeof(MensagensSucesso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria alterada com sucesso..
        /// </summary>
        public static string CategoriaAlterada {
            get {
                return ResourceManager.GetString("CategoriaAlterada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categoria excluída com sucesso..
        /// </summary>
        public static string CategoriaExcluida {
            get {
                return ResourceManager.GetString("CategoriaExcluida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário alterado com sucesso..
        /// </summary>
        public static string ComentarioAlterado {
            get {
                return ResourceManager.GetString("ComentarioAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário excluído com sucesso..
        /// </summary>
        public static string ComentarioExcluido {
            get {
                return ResourceManager.GetString("ComentarioExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil alterado com sucesso..
        /// </summary>
        public static string PerfilAlterado {
            get {
                return ResourceManager.GetString("PerfilAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil excluído com sucesso..
        /// </summary>
        public static string PerfilExcluido {
            get {
                return ResourceManager.GetString("PerfilExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post alterado com sucesso..
        /// </summary>
        public static string PostAlterado {
            get {
                return ResourceManager.GetString("PostAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post excluído com sucesso..
        /// </summary>
        public static string PostExcluido {
            get {
                return ResourceManager.GetString("PostExcluido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário alterado com sucesso..
        /// </summary>
        public static string UsuarioAlterado {
            get {
                return ResourceManager.GetString("UsuarioAlterado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário excluído com sucesso..
        /// </summary>
        public static string UsuarioExcluido {
            get {
                return ResourceManager.GetString("UsuarioExcluido", resourceCulture);
            }
        }
    }
}
